sudo: required
cache: bundler
dist: trusty
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
gemfiles:
  - normalizator.gemspec
script: "bundle exec rspec && bundle exec codeclimate-test-reporter"
before_install:
  - gem install bundler